### ISSUE TITLE
my (not so) simple json parser

### ISSUE THREAD

**Issue by theodelrieu** [pejman-hkh/json-parser#1]
https://github.com/nlohmann/json/

**Comment by udp** [comment]
It's kinda poor form* to advertise your own project by opening issues.  I just closed an issue from the author of this repo on my JSON parser, so I wouldn't expect people to do the same to them.

* rude

**Comment by theodelrieu** [comment]
He did the same on the mentioned repo, this was just a joke ;)

**Comment by udp** [comment]
Having said that,

https://github.com/aminroosta/sqlite_modern_cpp/issues/134
https://github.com/dropbox/json11/issues/111
https://github.com/nogden/xxsqlite/issues/7
https://github.com/facebook/hhvm/issues/7958
https://github.com/taocpp/json/issues/14
https://github.com/Zguy/Jzon/issues/19
https://github.com/nlohmann/json/issues/689
https://github.com/pejman-hkh/json-parser/issues/1
https://github.com/open-source-parsers/jsoncpp/issues/646
https://github.com/miloyip/nativejson-benchmark/issues/94
https://github.com/hjiang/jsonxx/issues/64
https://github.com/nbsdx/SimpleJSON/issues/9
https://github.com/MJPA/SimpleJSON/issues/37
https://github.com/pkoretic/sqlite_helper/issues/1
https://github.com/iwongu/sqlite3pp/issues/47
https://github.com/Dasister/mysql-cpp-api-wrapper/issues/1
https://github.com/SRombauts/SQLiteCpp/issues/135

... yeah they deserve it. 👍

**Comment by theodelrieu** [comment]
Btw you just referenced every issue :D

**Comment by udp** [comment]
shit

**Comment by pejman-hkh** [comment]
Your account has been flagged.
:cry:

**Comment by cgestes** [comment]
LOL
